stages:
  - build
  - deploy

variables:
  GIT_DEPTH: "1"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_TEST_IMAGE_X: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-x
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  CONTAINER_RELEASE_IMAGE_X: $CI_REGISTRY_IMAGE:X
  DOCKERHUB_RELEASE_IMAGE: nanahira/docker-mirai-cqhttp:latest
  DOCKERHUB_RELEASE_IMAGE_X: nanahira/docker-mirai-cqhttp:X

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  tags: 
    - docker
  script:
    - docker build --pull --no-cache -t $CONTAINER_TEST_IMAGE .
    - docker build -t $CONTAINER_TEST_IMAGE_X -f Dockerfile.x --build-arg BASE_IMAGE=$CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
    - docker push $CONTAINER_TEST_IMAGE_X

deploy_latest:
  stage: deploy
  tags: 
    - docker
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy_latest_x:
  stage: deploy
  tags: 
    - docker
  script:
    - docker pull $CONTAINER_TEST_IMAGE_X
    - docker tag $CONTAINER_TEST_IMAGE_X $CONTAINER_RELEASE_IMAGE_X
    - docker push $CONTAINER_RELEASE_IMAGE_X
  only:
    - master

deploy_dockerhub_latest:
  stage: deploy
  tags: 
    - docker
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $DOCKERHUB_RELEASE_IMAGE
    - docker push $DOCKERHUB_RELEASE_IMAGE
  only:
    - master

deploy_dockerhub_x:
  stage: deploy
  tags: 
    - docker
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker pull $CONTAINER_TEST_IMAGE_X
    - docker tag $CONTAINER_TEST_IMAGE_X $DOCKERHUB_RELEASE_IMAGE_X
    - docker push $DOCKERHUB_RELEASE_IMAGE_X
  only:
    - master

deploy_tag_x:
  stage: deploy
  tags: 
    - docker
  variables:
    CONTAINER_TAG_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_TAG_IMAGE
    - docker push $CONTAINER_TAG_IMAGE
  only:
    - tags
deploy_tag:
  stage: deploy
  tags: 
    - docker
  variables:
    CONTAINER_TAG_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-x
  script:
    - docker pull $CONTAINER_TEST_IMAGE_X
    - docker tag $CONTAINER_TEST_IMAGE_X $CONTAINER_TAG_IMAGE
    - docker push $CONTAINER_TAG_IMAGE
  only:
    - tags
